### ISSUE TITLE
How can i but the damage range higher ?

### ISSUE THREAD

**Issue by DragonfireHD** [OguzhanUmutlu/TreeCapitator#1]
The damage on the tree is just comes if you go in the Wood if he fall

**Comment by DragonfireHD** [comment]
And what is the max-block please explane i dont now that the plugin mean for 32 blocks

**Comment by OguzhanUmutlu** [comment]
Its the block amount that when you break some wood piece it starts scanning woods and leaves.
Try making a wood tower 33 block there will be 1 block on top when you break first block on bottom.
